#define GAMMA         1
#define E_PLUS        2
#define E_MINUS       3
#define MU_PLUS       5
#define MU_MINUS      6
#define PIO           7
#define PIP           8
#define PIM           9
#define TAU_PLUS     33 
#define TAU_MINUS    34
#define W_PLUS       42
#define W_MINUS      43
#define Z_ZERO       44
#define HIGGS        54
#define NU_E         58
#define NU_E_BAR     59
#define NU_MU        60
#define NU_MU_BAR    61
#define NU_TAU       62 
#define NU_TAU_BAR   63
#define GLUON       100
#define U_QUARK     101
#define D_QUARK     102
#define S_QUARK     103
#define C_QUARK     104 
#define U_QUARK_BAR 107
#define D_QUARK_BAR 108
#define S_QUARK_BAR 109
#define C_QUARK_BAR 110
